# --
# File: logrhythmsiem_consts.py
#
# Copyright (c) Phantom Cyber Corporation, 2017
#
# This unpublished material is proprietary to Phantom Cyber.
# All rights reserved. The methods and
# techniques described herein are considered trade secrets
# and/or confidential. Reproduction or distribution, in whole
# or in part, is forbidden except by express written permission
# of Phantom Cyber.
#
# --

LOGRHYTHMSIEM_ALARM_SERVICE = "AlarmServiceBasicAuth.svc?wsdl"
LOGRHYTHMSIEM_ENTITY_SERVICE = "EntityServiceBasicAuth.svc?wsdl"
LOGRHYTHMSIEM_HOST_SERVICE = "HostServiceBasicAuth.svc?wsdl"
LOGRHYTHMSIEM_LIST_SERVICE = "ListServiceBasicAuth.svc?wsdl"
LOGRHYTHMSIEM_LOG_QUERY_SERVICE = "LogQueryServiceBasicAuth.svc?wsdl"
LOGRHYTHMSIEM_LOOKUP_SERVICE = "LookupServiceBasicAuth.svc?wsdl"

LOGRHYTHMSIEM_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%f"

LOGRHYTHMSIEM_LIST_SERVICE_DICT = {"General": "AddGeneralListItem",
                                   "Hostname": "AddHostListItemHostname",
                                   "IP": "AddHostListItemIPAddress",
                                   "IP Range": "AddHostListItemIPAddressRange",
                                   "Known Host": "AddHostListItemKnownHost",
                                   "User": "AddUserListItem"}

LOGRHYTHMSIEM_FILTER_DICT = {
        "account": "Account",
        "address": "Address",
        "amount": "Amount",
        "application": "Application",
        "bytesin": "BytesIn",
        "bytesinout": "BytesInOut",
        "bytesout": "BytesOut",
        "classification": "Classification",
        "command": "Command",
        "commonevent": "CommonEvent",
        "description": "Description",
        "direction": "Direction",
        "domain": "Domain",
        "duration": "Duration",
        "entity": "Entity",
        "group": "Group",
        "host": "Host",
        "hostname": "HostName",
        "idmgroupforaccount": "IDMGroupForAccount",
        "idmgroupforlogin": "IDMGroupForLogin",
        "idmgroupforuser": "IDMGroupForUser",
        "impactedentity": "ImpactedEntity",
        "impactedhost": "ImpactedHost",
        "impactedhostname": "ImpactedHostName",
        "impactedinterface": "ImpactedInterface",
        "impactedip": "ImpactedIP",
        "impactediprange": "ImpactedIPRange",
        "impactedlocation": "ImpactedLocation",
        "impactedmac": "ImpactedMAC",
        "impactednatip": "ImpactedNATIP",
        "impactednatiprange": "ImpactedNATIPRange",
        "impactednatport": "ImpactedNATPort",
        "impactednatportrange": "ImpactedNATPortRange",
        "impactednetwork": "ImpactedNetwork",
        "impactedport": "ImpactedPort",
        "impactedportrange": "ImpactedPortRange",
        "impactedzone": "ImpactedZone",
        "interface": "Interface",
        "ip": "IP",
        "iprange": "IPRange",
        "itemsin": "ItemsIn",
        "itemsinout": "ItemsInOut",
        "itemsout": "ItemsOut",
        "knownhost": "KnownHost",
        "knownimpactedhost": "KnownImpactedHost",
        "knownoriginhost": "KnownOriginHost",
        "knownservice": "KnownService",
        "location": "Location",
        "login": "Login",
        "mac": "MAC",
        "message": "Message",
        "mperule": "MPERule",
        "msgsource": "MsgSource",
        "msgsourcehost": "MsgSourceHost",
        "msgsourcetype": "MsgSourceType",
        "natip": "NATIP",
        "natiprange": "NATIPRange",
        "natport": "NATPort",
        "natportrange": "NATPortRange",
        "network": "Network",
        "normalmsgdate": "NormalMsgDate",
        "normalmsgdaterange": "NormalMsgDateRange",
        "object": "Object",
        "objectname": "ObjectName",
        "originentity": "OriginEntity",
        "originentityorimpactedentity": "OriginEntityOrImpactedEntity",
        "originhost": "OriginHost",
        "originhostname": "OriginHostName",
        "origininterface": "OriginInterface",
        "originip": "OriginIP",
        "originiprange": "OriginIPRange",
        "originlocation": "OriginLocation",
        "originmac": "OriginMAC",
        "originnatip": "OriginNATIP",
        "originnatiprange": "OriginNATIPRange",
        "originnatport": "OriginNATPort",
        "originnatportrange": "OriginNATPortRange",
        "originnetwork": "OriginNetwork",
        "originport": "OriginPort",
        "originportrange": "OriginPortRange",
        "originzone": "OriginZone",
        "originzoneorimpactedzone": "OriginZoneOrImpactedZone",
        "pid": "PID",
        "port": "Port",
        "portrange": "PortRange",
        "priority": "Priority",
        "process": "Process",
        "protocol": "Protocol",
        "quantity": "Quantity",
        "rate": "Rate",
        "recipient": "Recipient",
        "sender": "Sender",
        "session": "Session",
        "severity": "Severity",
        "size": "Size",
        "subject": "Subject",
        "timeofday": "TimeOfDay",
        "url": "URL",
        "user": "User",
        "vendormsgid": "VendorMsgID",
        "version": "Version"
    }

LOGRHYTHMSIEM_VALUE_TYPE_DICT = {
        "account": "string",
        "address": "ip",
        "amount": "quantity",
        "application": "string",
        "bytesin": "byte",
        "bytesinout": "byte",
        "bytesout": "byte",
        "classification": "integer",
        "command": "string",
        "commonevent": "integer",
        "direction": "byte",
        "domain": "string",
        "duration": "string",
        "entity": "integer",
        "group": "string",
        "host": "string",
        "hostname": "string",
        "idmgroupforaccount": "string",
        "idmgroupforlogin": "string",
        "idmgroupforuser": "string",
        "impactedentity": "string",
        "impactedhost": "string",
        "impactedhostname": "string",
        "impactedinterface": "string",
        "impactedip": "ip",
        "impactediprange": "ip",
        "impactedlocation": "string",
        "impactedmac": "string",
        "impactednatip": "ip",
        "impactednatiprange": "ip",
        "impactednatport": "port",
        "impactednatportrange": "port",
        "impactednetwork": "string",
        "impactedport": "port",
        "impactedportrange": "port",
        "impactedzone": "string",
        "interface": "string",
        "ip": "ip",
        "iprange": "ip",
        "itemsin": "integer",
        "itemsinout": "integer",
        "itemsout": "integer",
        "knownhost": "string",
        "knownimpactedhost": "string",
        "knownoriginhost": "string",
        "knownservice": "string",
        "location": "string",
        "login": "string",
        "mac": "string",
        "message": "string",
        "mperule": "string",
        "msgsource": "string",
        "msgsourcehost": "string",
        "msgsourcetype": "string",
        "natip": "ip",
        "natiprange": "ip",
        "natport": "port",
        "natportrange": "port",
        "network": "string",
        "normalmsgdate": "string",
        "normalmsgdaterange": "string",
        "object": "string",
        "objectname": "string",
        "originentity": "string",
        "originentityorimpactedentity": "string",
        "originhost": "string",
        "originhostname": "string",
        "origininterface": "string",
        "originip": "ip",
        "originiprange": "ip",
        "originlocation": "string",
        "originmac": "string",
        "originnatip": "ip",
        "originnatiprange": "ip",
        "originnatport": "port",
        "originnatportrange": "port",
        "originnetwork": "string",
        "originport": "port",
        "originportrange": "port",
        "originzone": "string",
        "originzoneorimpactedzone": "string",
        "pid": "quantity",
        "port": "port",
        "portrange": "port",
        "priority": "quantity",
        "process": "string",
        "protocol": "string",
        "quantity": "quantity",
        "rate": "quantity",
        "recipient": "string",
        "sender": "string",
        "session": "quantity",
        "severity": "quantity",
        "size": "quantity",
        "subject": "string",
        "timeofday": "string",
        "url": "string",
        "user": "string",
        "vendormsgid": "string",
        "version": "string"
    }
